name: generate-snake-game-from-github-contribution-grid
uses: Platane/snk@v3.3.0
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aryanraj17
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
